### ISSUE TITLE
strings have whitespace

### ISSUE THREAD

**Issue by sckott** [AldoCompagnoni/popler_API#5]
@AldoCompagnoni many strings in the database have whitespace around the meaningful characters e.g., 

" Heteromyoxyuris"
" deserti"

it seems to mostly affect genus and species fields so far that I can tell

is this planned to be fixed? or maybe the whitespace is meaningful somehow?

**Comment by AldoCompagnoni** [comment]
This are mistakes in the original data, and potentially mistakes we have included. 
This is not useful, and I had rarely noticed it - but if in your experience it is a recurring problem, I will gladly fix it!

**Comment by sckott** [comment]
it's a problem becuase the user then has to put a space in their query, and they won't know when and when not to do that. e.g., for " Syphacia" they need to do 

https://popler.space/search?proj_metadata_key=25&genus=%20Syphacia

`%20` is the url encoded code for a space

instead of simply

https://popler.space/search?proj_metadata_key=25&genus=Syphacia

without the space

**Comment by AldoCompagnoni** [comment]
Good call, I need to fix this!

**Comment by sckott** [comment]
ok

**Comment by AldoCompagnoni** [comment]
I have removed white spaces for variables `kingdom`, `phylum`, `clss`, `subclass`, `ordr`, `family`, `genus`, `species`, and `common_name`!

**Comment by sckott** [comment]
cool. when you get me a new dump I can get it loaded in
